#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail

[ "$(/usr/bin/id -u)" == "0" ] || exec sudo -EH "${0}" "${@}"

CRI_SOCKETS=(/var/run/cri-dockerd.sock /var/run/crio/crio.sock /var/run/containerd/containerd.sock)
for SOCKET in "${CRI_SOCKETS[@]}" ; do
	if [ -S "${SOCKET}" ] ; then
		CRI=(--cri-socket "unix://${SOCKET}")
		break
	fi
done

echo_run()
{
	local ARGS=("${@}")
	echo "${ARGS[@]@Q}"
	"${@}"
}

# Clean house
echo_run kubeadm reset -f "${CRI[@]}"
[ -d /etc/cni/net.d ] && rm -rf /etc/cni/net.d
if [ -f "${HOME}/.kube/config" ] ; then
	for n in context cluster user ; do
		kubectl config delete-$n local || true
	done
fi
rm -f /usr/local/share/ca-certificates/k8s-ca.crt

CA_UPDATER=(update-ca-trust update-ca-certificates)
for ca in "${CA_UPDATER[@]}" ; do
	if type -P "${ca}" &>/dev/null ; then
		RC=0
		echo_run "${ca}" || RC=${?}
		[ ${RC} -eq 0 ] || echo "WARNING: ${ca} returned ${RC} ... certificate trusts may be incomplete!"
		break
	fi
done

CONN="K8s-Local"
if nmcli con show "${CONN}" &>/dev/null ; then
	echo_run nmcli con del "${CONN}"
fi

SYSTEMD_DIR="/etc/systemd"

IFACE="kubelocal0"
NETWORK_DIR="${SYSTEMD_DIR}/network"
rm -rvf "${NETWORK_DIR}/10-${IFACE}".net* &>/dev/null || true
systemctl status systemd-networkd.service &>/dev/null && \
	echo_run systemctl restart systemd-networkd.service

RESOLVE_DIR="${SYSTEMD_DIR}/resolved.conf.d"
rm -rvf "${RESOLVE_DIR}"/k8s-*.conf "${RESOLVE_DIR}/00-listen-on-${IFACE}.conf"
systemctl status systemd-resolved.service &>/dev/null && \
	echo_run systemctl restart systemd-resolved.service

echo_run systemctl stop kubelet
