#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail

timestamp()
{
	/usr/bin/date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

fail()
{
	say "❌ ${@}" 1>&2
	exit ${EXIT_CODE:-1}
}

cleanup()
{
	if [ -v KUBEADM_CONFIG_FILE ] ; then
		[ -n "${KUBEADM_CONFIG_FILE}" ] && rm -f "${KUBEADM_CONFIG_FILE}" &>/dev/null || true
	fi
}

echo_run()
{
	local ARGS=("${@}")
	echo "${ARGS[@]@Q}"
	"${@}"
}

trap cleanup EXIT

CRI_SOCKETS=(/var/run/cri-dockerd.sock /var/run/crio/crio.sock /var/run/containerd/containerd.sock)
CRI=""
for SOCKET in "${CRI_SOCKETS[@]}" ; do
	if [ -S "${SOCKET}" ] ; then
		CRI="unix://${SOCKET}"
		break
	fi
done
[ -n "${CRI}" ] || fail "❌ Failed to find the CRI socket from the candidates [${CRI_SOCKETS[@]}]"

[ -v CLUSTER_CIDR ] || CLUSTER_CIDR="10.96.0.0/12"
[ -v SERVICE_CIDR ] || SERVICE_CIDR="${CLUSTER_CIDR}"

LOCAL_ONLY_NAME="K8s-Local"
LOCAL_ONLY_ENDPOINT="k8s.cluster.prv"
LOCAL_ONLY_IFACE="kubelocal0"
LOCAL_ONLY_ADDX="10.255.255.254"

LAN_FQDN="$(hostname -f)"
LAN_HOSTNAME="$(hostname -s)"

LAN_ADDRESSES=""
while read DEV ; do
	ADDRESSES="$(nmcli -g 'ip4.address' dev show "${DEV}" | sed -e 's;\s*|\s*;", ";g' -e 's;/..;;g' -e 's;^\s*;;g' -e 's;\s*$;;g')"
	[ -n "${ADDRESSES}" ] || continue

	# Add a separator between address batches, if necessary
	[ -n "${LAN_ADDRESSES}" ] && LAN_ADDRESSES+='", "'

	LAN_ADDRESSES+="${ADDRESSES}"
done < <(nmcli -g device,type conn show --active 2>/dev/null | grep -- 'ethernet$' | sed -e 's;:.*$;;g')

# We expressly don't add a leading or trailing double-quote
# because that's added expressly down below. We do this for
# syntactic consistency there.

# From what we've seen, this is harmless if used all the time. However,
# the exposure of this variable means that we can easily enough initialize
# control plane nodes designed to use a shared endpoint IP (remember to
# set up the HAP facade first!).
[ -v CONTROL_PLANE_ENDPOINT ] || CONTROL_PLANE_ENDPOINT=""
[ -n "${CONTROL_PLANE_ENDPOINT}" ] || CONTROL_PLANE_ENDPOINT="${LOCAL_ONLY_ENDPOINT}"

if [ "${CONTROL_PLANE_ENDPOINT}" == "${LOCAL_ONLY_ENDPOINT}" ] ; then

	# Make sure the virtual interface exists
	say "👉 Creating the ${LOCAL_ONLY_IFACE} virtual interface..."

	# First things first ... use NetworkManager (nmcli) or Systemd-Networkd?
	if nmcli con show --active &>/dev/null ; then
		if nmcli con show "${LOCAL_ONLY_NAME}" &>/dev/null ; then
			say "\t✅ The interface already exists!"
		else
			nmcli conn add type dummy con-name "${LOCAL_ONLY_NAME}" ifname "${LOCAL_ONLY_IFACE}" ip4 "${LOCAL_ONLY_ADDX}/32" || fail "Failed to create the K8s virtual interface"
			say "\t✅ The interface was created!"
		fi
	elif systemctl status systemd-networkd.service &>/dev/null ; then
		SYSTEMD_DIR="/etc/systemd/network"
		[ -d "${SYSTEMD_DIR}" ] || mkdir -p "${SYSTEMD_DIR}" || fail "Failed to locate or create the network directory at [${SYSTEMD_DIR}]"

		# Do the Systemd-Networkd configuration
		cat >> "/etc/systemd/network/10-${LOCAL_ONLY_IFACE}.netdev" <<-EOF
		[NetDev]
		Name=${LOCAL_ONLY_IFACE}
		Kind=dummy
		EOF

		cat >> "/etc/systemd/network/10-${LOCAL_ONLY_IFACE}.network" <<-EOF
		[Match]
		Name=${LOCAL_ONLY_IFACE}

		[Network]
		Address=${LOCAL_ONLY_ADDX}/32
		EOF

		systemctl restart systemd-networkd.service || fail "Failed to restart the networking service"
	else
		fail "You must have either NetworkManager or systemd-networkd running to configure the persistent virtual interface, or configure it manually beforehand (name=${LOCAL_ONLY_IFACE}, preferred IP=${LOCAL_ONLY_ADDX})"
	fi

	POLL_TIMEOUT=30
	START="$(date +%s)"
	while true ; do
		read INET ADDX BRD BCAST REST < <(ip addr show "${LOCAL_ONLY_IFACE}" | egrep '^[[:space:]]*inet[[:space:]]+(0|[1-9])') || true
		if [ -n "${ADDX}" ] ; then
			LOCAL_ONLY_ADDX="${ADDX%%/*}"
			break
		fi

		# No IP address yet ... have we waited long enough?
		NOW="$(date +%s)"
		[ $(( NOW - START )) -ge ${POLL_TIMEOUT} ] && fail "Failed to query the IP address for the interface '${LOCAL_ONLY_IFACE}'"
		sleep 1 || fail "Sleep interrupted, cannot continue"
	done

	say "\t✅ The interface is assigned address [${LOCAL_ONLY_ADDX}]"

	# Make sure the virtual interface's IP address is listed in /etc/hosts
	FILTERED_HOSTS="$(cat /etc/hosts | sed -e "/^.*\s${LOCAL_ONLY_ENDPOINT}\(\s.*\)\?$/d")"
	cat > /etc/hosts <<-EOF
	${FILTERED_HOSTS}
	${LOCAL_ONLY_ADDX} ${LOCAL_ONLY_ENDPOINT}
	EOF
fi

echo_run systemctl stop kubelet || true
echo_run systemctl start kubelet || fail "Failed to start kubelet"

KUBEADM_CONFIG=""
read -r -d '' VAR <<-EOF || true
	---
	apiVersion: kubeadm.k8s.io/v1beta3
	kind: InitConfiguration
	nodeRegistration:
	  criSocket: ${CRI}
EOF
KUBEADM_CONFIG+="${VAR}"
KUBEADM_CONFIG+=$'\n'

if [ "${CONTROL_PLANE_ENDPOINT}" == "${LOCAL_ONLY_ENDPOINT}" ] ; then
	read -r -d '' VAR <<-EOF || true
		localAPIEndpoint:
		  advertiseAddress: ${LOCAL_ONLY_ADDX}
	EOF
	KUBEADM_CONFIG+="${VAR}"
	KUBEADM_CONFIG+=$'\n'
fi

read -r -d '' VAR <<-EOF || true
	---
	apiVersion: kubeadm.k8s.io/v1beta3
	kind: ClusterConfiguration
	controlPlaneEndpoint: ${CONTROL_PLANE_ENDPOINT}
	networking:
	  serviceSubnet: ${SERVICE_CIDR}
	  podSubnet: ${CLUSTER_CIDR}
EOF
KUBEADM_CONFIG+="${VAR}"
KUBEADM_CONFIG+=$'\n'

if [ "${CONTROL_PLANE_ENDPOINT}" == "${LOCAL_ONLY_ENDPOINT}" ] ; then
	read -r -d '' VAR <<-EOF || true
		apiServer:
		  certSANs: &cert-sans [ "127.0.0.1", "localhost", "localhost.localdomain", "${LOCAL_ONLY_ENDPOINT}", "${LAN_HOSTNAME}", "${LAN_FQDN}", "${LAN_ADDRESSES}" ]
		etcd:
		  local:
		    serverCertSANs: *cert-sans
		    peerCertSANs: *cert-sans
		    extraArgs:
		      listen-client-urls: https://${LOCAL_ONLY_ADDX}:2379
		      advertise-client-urls: https://${LOCAL_ONLY_ADDX}:2379
		      listen-peer-urls: https://${LOCAL_ONLY_ADDX}:2380
		      initial-advertise-peer-urls: https://${LOCAL_ONLY_ADDX}:2380
	EOF
	KUBEADM_CONFIG+="${VAR}"
	KUBEADM_CONFIG+=$'\n'
fi

KUBEADM_CONFIG_FILE="$(mktemp --suffix=.yaml)"
echo "${KUBEADM_CONFIG}" > "${KUBEADM_CONFIG_FILE}"

# Ensure we have br_netfilter
modprobe br_netfilter || fail "Failed to install the netfilter bridging module"
K8S_SYSCTL="/etc/sysctl.d/99-kubernetes.conf"
cat <<EOF > "${K8S_SYSCTL}"
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
EOF
echo_run sysctl -p "${K8S_SYSCTL}" || fail "Failed to enable network bridging"

# Next, init the cluster
echo_run kubeadm init \
	--config "${KUBEADM_CONFIG_FILE}" \
	--upload-certs || fail "Failed to run the kubeadm init command"

CA_UPDATER=()
CA_UPDATER+=(update-ca-trust:/etc/pki/ca-trust/source/anchors)
CA_UPDATER+=(update-ca-certificates:/usr/local/share/ca-certificates/)
for updater in "${CA_UPDATER[@]}" ; do
	IFS=":" read ca target <<< "${updater}"
	if type -P "${ca}" &>/dev/null ; then
		echo_run cp -vf /etc/kubernetes/pki/ca.crt "${target}"/k8s-ca.crt
		RC=0
		echo_run "${ca}" || RC=${?}
		[ ${RC} -eq 0 ] || echo "WARNING: ${ca} returned ${RC} ... certificate trusts may be incomplete!"
		break
	fi
done

# Set up the kubeconfig stuff
"${BASEDIR}/init-kubeconfig"

# This will need to be run after each added node
echo_run kubectl --context "local" taint nodes --all node-role.kubernetes.io/master- || true
# ONLY FOR SINGLE-NODE CLUSTERS
echo_run kubectl --context "local" taint nodes --all node-role.kubernetes.io/control-plane- || true

# Some short display stuff
echo_run kubectl --context "local" get nodes
echo_run kubectl --context "local" get pods --all-namespaces
