#!/bin/bash
SCRIPT="$(readlink -f "${BASH_SOURCE:-${0}}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail

timestamp()
{
	date -Ins -u
}

say()
{
	echo -e "$(timestamp): ${@}"
}

err()
{
	say "❌ ${@}"
}

fail()
{
	err "${@}"
	exit ${EXIT_CODE:-1}
}

CURRENT_USER="$(id -un)"
HOME="$(eval echo ~${CURRENT_USER})"

if [ ! -d "${HOME}" ] ; then
	err "❌ No home directory [${HOME}] for user [${CURRENT_USER}] ... can't configure AWS"
	exit 0
fi

#
# Set up the AWS configuration
#
[ -v AWS_CONFIG ] || AWS_CONFIG="${HOME}/.aws/config"
[ -v AWS_CREDS ] || AWS_CREDS="${HOME}/.aws/credentials"
[ -v AWS_PROFILE ] || AWS_PROFILE="armedia-marketplace"

if [ -f "${AWS_CONFIG}" ] ; then
	say "✅ The AWS configuration is already created at [${AWS_CONFIG}] for user ${CURRENT_USER}..."

	# Remove any existing "armedia-marketplace" profiles
	say "👉 Removing the existing ${AWS_PROFILE} profile from the AWS configuration..."
	sed -i \
		-e '/^\s*\[\s*profile\s\+'"${AWS_PROFILE}"'\s*\]\s*$/,/^\s*\[/{/^\s*\[\s*profile\s\+'"${AWS_PROFILE}"'\s*\]\s*$/d;/^\s*\[/!d}' \
		-e '/^\s*\[\s*'"${AWS_PROFILE}"'\s*\]\s*$/,/^\s*\[/{/^\s*\[\s*'"${AWS_PROFILE}"'\s*\]\s*$/d;/^\s*\[/!d}' \
		"${AWS_CONFIG}"
else
	say "👉 Creating your AWS configuration for user ${CURRENT_USER}..."
	mkdir -p "$(dirname "${AWS_CONFIG}")"
	cat <<-EOF > "${AWS_CONFIG}"
	[default]
	region=us-east-1
	EOF
fi

say "👉 Adding the ${AWS_PROFILE} profile to the AWS configuration at [${AWS_CONFIG}]..."
cat <<-EOF >> "${AWS_CONFIG}"

[profile ${AWS_PROFILE}]
region = us-east-1
EOF
say "✅ Profile added!"

CREDS="${BASEDIR}/aws-marketplace.bin"

if [ -f "${CREDS}" ] ; then
	say "🔑 Decrypting the AWS credentials..."
	if CREDS="$(openssl aes-256-cbc -a -A -d -salt -iter 1000 -in "${CREDS}")" ; then
		if [ -f "${AWS_CREDS}" ] ; then
			say "✅ The AWS credentials are already created at [${AWS_CREDS}] for user ${CURRENT_USER}..."

			# Remove any existing "armedia-marketplace" profiles
			say "👉 Removing the existing ${AWS_PROFILE} profile from the AWS credentials..."
			sed -i \
				-e '/^\s*\[\s*'"${AWS_PROFILE}"'\s*\]\s*$/,/^\s*\[/{/^\s*\[\s*'"${AWS_PROFILE}"'\s*\]\s*$/d;/^\s*\[/!d}' \
				"${AWS_CREDS}"
		fi
		cat <<-EOF >> "${AWS_CREDS}"
		[${AWS_PROFILE}]
		${CREDS}
		EOF
		say "🔓 Credentials decrypted and configured!"
	else
		err "Unable to decrypt the credentials for AWS..."
		CREDS=""
	fi
else
	CREDS=""
fi

if [ -z "${CREDS}" ] ; then
	say "👉 Please remember to add the AWS credentials to the credentials file at [${AWS_CREDS}], like so:"
	cat <<-EOF
	[${AWS_PROFILE}]
	aws_access_key_id=\${YOUR_AWS_ACCESS_KEY_ID}
	aws_secret_access_key=\${YOUR_AWS_SECRET_ACCESS_KEY}
	EOF
fi
exit 0
