#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -euo pipefail

CERT="/etc/kubernetes/pki/ca.crt"
TEMPFILE="/tmp/k8s-ca.crt"
cleanup()
{
	rm -rf "${TEMPFILE}" &>/dev/null || return 0
}

cp -vf "${CERT}" "${TEMPFILE}"
trap cleanup EXIT

"${BASEDIR}/trust-cert" "${TEMPFILE}"
