#!/bin/bash
SCRIPT="$(readlink -f "${0}")"
BASEDIR="$(dirname "${SCRIPT}")"
SCRIPT="$(basename "${SCRIPT}")"

set -e -o pipefail

echo_run()
{
	local ARGS=("${@}")
	echo "${ARGS[@]@Q}"
	"${@}"
}

[ -v METRICS_VERSION ] || METRICS_VERSION=""
[ -n "${METRICS_VERSION}" ] || METRICS_VERSION="latest"

METRICS_URL="https://github.com/kubernetes-sigs/metrics-server/releases/${METRICS_VERSION}/download/components.yaml"
METRICS_FILE="components.yaml"

echo "Downloading the metrics version file..."
YAML="$(curl -fsSL "${METRICS_URL}")" || { echo "Failed to download the metrics yaml" ; exit 1 ; }
echo "Creating the metrics resources"
echo_run kubectl --context "local" apply -f - < <(echo "${YAML}" | sed '/--metric-resolution=/a \ \ \ \ \ \ \ \ - --kubelet-insecure-tls')
